apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: mysql
          image: 931058976119.dkr.ecr.us-east-1.amazonaws.com/insurance-fraud-detection-db:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "password"
            - name: MYSQL_DATABASE
              value: "flaskapp"
            - name: MYSQL_USER
              value: "flaskuser"
            - name: MYSQL_PASSWORD
              value: "password"
          livenessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
            initialDelaySeconds: 30
            periodSeconds: 10
      imagePullSecrets:
      - name: aws-ecr-secret
